on:
  push:
  workflow_dispatch:

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: make clean demo
      - run: |-
          git checkout -- .
          make demo
